### ISSUE TITLE
Fix missing check that ranger's authorization challenge is solved 

### ISSUE THREAD

**Issue by kovetskiy** [rubykube/peatio-trading-ui#106]
trading-ui does send jwt token to ranger, but there is no check that authorization challenge is solved, need to add the check and show an alert if authorization is failed.

Good example of such check is here: https://github.com/rubykube/ranger-example-nodejs

related issues #102 #105

**Comment by huuhait** [comment]
Not working
![image](https://user-images.githubusercontent.com/40519768/47271476-0466d100-d5a4-11e8-8c78-97294b694a71.png)
![image](https://user-images.githubusercontent.com/40519768/47271481-1ba5be80-d5a4-11e8-8236-d3f823172f09.png)
and after refresh page
![image](https://user-images.githubusercontent.com/40519768/47271487-26605380-d5a4-11e8-8964-becf68a91ef0.png)

**Comment by huuhait** [comment]
node app.js Not update

node app.js --jwt (JWT PRIVATE KEY) = [ERROR] Authentication failed.
![image](https://user-images.githubusercontent.com/40519768/47272433-eacb8680-d5af-11e8-9dde-40b6d5eb786f.png)

**Comment by nantestdeveloper** [comment]
@Thedabest  have you resolved this issue?
Using peatio 1.8.51 ,not able to start the ranger services on local dev env. any idea how to start?

**Comment by huuhait** [comment]
fixed

**Comment by omgnotagain** [comment]
@huuhait can you please tell me how did you manage to solve this issue. I have the exact same problem tried also with ranger node test script, same results.

**Comment by Changsst** [comment]
> fixed

@huuhait how u managed to fix?
