### ISSUE TITLE
URI::InvalidURIError in MarketsController#show

### ISSUE THREAD

**Issue by endofthepain** [rubykube/peatio-trading-ui#14]
![screenshot_403](https://user-images.githubusercontent.com/11496089/38306870-16bc905c-383c-11e8-8169-615bf455fb7c.png)

.__. any solutions ?

**Comment by yivo** [comment]
Thank you for the report.

1. Please, provide versions you are using.
2. Provide configuration vars.

**Comment by endofthepain** [comment]
i am using peatio 1.6 and peatio trading ui 1.6
and here my configurations on application.yml 

![screenshot_405](https://user-images.githubusercontent.com/11496089/38318726-38d34fdc-385a-11e8-9afe-287f01f0791b.png)

everything runing smoothly when run peatio 1.5 but when i update to 1.6 i get this error

**Comment by yivo** [comment]
@endofthepain I need also configs for trading-ui

**Comment by lizhuomeng71** [comment]
experience the same issue after move to 1.6

**Comment by yivo** [comment]
@lizhuomeng71 can you share the configs?

**Comment by Tach-Yon** [comment]
Same issues. Do you suppose this is a config issue? I'm gonna keep trying.

**Comment by yivo** [comment]
This is config issue. Please, double-check your ENV variables at peatio-trading-ui. Be sure you don't have double http in URL.

**Comment by dsuwirya** [comment]
I'm getting the same error as the second screenshot above, can anybody help to tell how this was resolved exactly?
