### ISSUE TITLE
How to setup trading ui

### ISSUE THREAD

**Issue by esoftllp** [rubykube/peatio-trading-ui#15]
Hi have successfully setup peatio admin panel but i am unable to setup trading ui.I have some doubts.

1. Where to clone all trading ui files .Will it be within peatio folder or it be any location.
2. There is no mapping option in nginx.config for trading ui.
3. I have copied nginx.conf fro ci/nginx.conf but after this i am not getting any webpage .

Can you help me to setup trading ui.

Thanks

**Comment by yivo** [comment]
@esoftllp Please, check https://github.com/rubykube/peatio/issues/738

**Comment by yivo** [comment]
Trading UI is JUST another app.

**Comment by yivo** [comment]
Deploy it as usual.
