### ISSUE TITLE
Key not found

### ISSUE THREAD

**Issue by esoftllp** [rubykube/peatio-trading-ui#16]
Please check attached image and let me know what is wrong.

![capture](https://user-images.githubusercontent.com/32095632/38407158-376b332a-392d-11e8-831f-6ba74df37668.PNG)

**Comment by yivo** [comment]
@esoftllp I think you missed `bin/init_config`.

**Comment by archana209** [comment]
@yivo I have run the bin/config but I am still getting error shown above.

 in my peatio-trading-ui/config/application.yml

**PLATFORM_ROOT_URL: http://myhost.tk**

in my peatio/config/application.yml

//cant put 3000 here as google oauth fails 
**URL_HOST: myhost.tk**
URL_SCHEME: http

peatio/ci/nginx/server.conf
server_name myhost.tk;

Do I need to supply port in URL_HOST  to fix above?
