### ISSUE TITLE
KeyError in Markets#show

### ISSUE THREAD

**Issue by esoftllp** [rubykube/peatio-trading-ui#17]
I am getting this error

![capture](https://user-images.githubusercontent.com/32095632/38441537-eb520604-3999-11e8-88cf-5dab67388378.PNG)

**Comment by archana209** [comment]
@esoftllp : Can you please review my config to point out how you got past this error?
my setup is on ubuntu

in my p**eatio-trading-ui/config/application.yml**

PLATFORM_ROOT_URL: http://myhost.tk

in my **peatio/config/application.yml**

//cant put 3000 here as google oauth fails
URL_HOST: myhost.tk
URL_SCHEME: http

**peatio/ci/nginx/server.conf**

server_name myhost.tk;

my **/etc/nginx/sites-available/default**

server {
  server_name myhost.tk;
  listen      80 default_server;

  location ~ ^/(?:trading|trading-ui-assets)\/ {
    proxy_pass http://127.0.0.1:4000;
  }

  location / {
    proxy_pass http://127.0.0.1:3000;
  }
}

**Comment by squallcx** [comment]
I also have the same problem, how to solve
