### ISSUE TITLE
Charts building issue

### ISSUE THREAD

**Issue by pkucherenk0** [rubykube/peatio-trading-ui#26]
This issue can be found in exchange of UAH/* and if you have option "Candlestick" active.
![selection_048](https://user-images.githubusercontent.com/38254545/38684366-354ee280-3e78-11e8-9d39-f6cdc332b717.png)

Next issue can be recreated if the chart are empty at the first place like below:
![selection_053](https://user-images.githubusercontent.com/38254545/38685261-26c6d9e6-3e7a-11e8-8ec9-aab0a756c60e.png)
Make any transaction and you will get forever loading
![selection_052](https://user-images.githubusercontent.com/38254545/38685327-54a6fc6a-3e7a-11e8-9cb8-535972f49947.png)

**Comment by antonror** [comment]
Hi, I'm having the same issue when I start trading with a newly created database.

**Comment by jdowning100** [comment]
I'm also having that issue, but the error is different. The JSON request returns {"error":{"code":1001,"message":"market does not have a valid value"}} and the console logs: Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)
Any solutions to this problem?

**Comment by yivo** [comment]
Fixed in #39.
