### ISSUE TITLE
Candlestick is not showing properly

### ISSUE THREAD

**Issue by batutot** [rubykube/peatio-trading-ui#27]
Open market view : 

![image](https://user-images.githubusercontent.com/16070344/39080518-9a9000f2-4530-11e8-835c-305e58d37f1e.png)

Click on LINE:

![image](https://user-images.githubusercontent.com/16070344/39080525-b96b73f8-4530-11e8-8967-9a4f20eddf7f.png)

And then click back on CANDLESTICK:

![image](https://user-images.githubusercontent.com/16070344/39080537-f11b50f2-4530-11e8-90cb-8ca810ac9aba.png)

The green/red candlestick/candlesticks are not showing for the all timeline.  Just for the selected time range.

**Comment by Sophrinix** [comment]
Can you do me a favor and do a mysql dump of your orders and trades table. At a minimum, maybe 10 rows from each of those tables, but ideally a full dump? This is an issue I am very motivated to fix.

**Comment by batutot** [comment]
it is from http://peatio.trade/

**Comment by batutot** [comment]
@dinesh-skyach 

please check 1m, 5m and 15m. 

thx,

**Comment by yivo** [comment]
Fixed in #35.
