### ISSUE TITLE
TypeError in Markets#show

### ISSUE THREAD

**Issue by esoftllp** [rubykube/peatio-trading-ui#28]
Hi @yivo 

Getting this error in ver 1.7 stable

![capture](https://user-images.githubusercontent.com/32095632/39287518-b5052290-4941-11e8-812d-d60cab819dc4.PNG)

**Comment by yivo** [comment]
Hi @esoftllp 

Market ID is always string in 1.6 and up. You probably use peatio 1.5 or something line. You should use 1.7.

**Comment by esoftllp** [comment]
Please check attached screenshot.I am using 1.7 stable branch

![capture](https://user-images.githubusercontent.com/32095632/39289244-e2d09d7e-4948-11e8-98ee-59495785d443.PNG)

**Comment by yivo** [comment]
@esoftllp please re-read what I wrote to you: use peatio 1.7 and trading UI 1.7 and do migrations very very carefully and correctly.

**Comment by esoftllp** [comment]
@yivo I have cheked out 1.7 branch for both UI and peatio.Let me know what i am doing wrong.I checked version it is running on 1.7.4 of peatio.Let me know how i can use Version 1.7 for both Trading Ui and Peatio.

Thanks in Advance

**Comment by yivo** [comment]
@esoftllp Peatio 1.6 and up uses string IDs for markets, previous version use numeric. I am sure you missed something with versions.

**Comment by yivo** [comment]
https://github.com/rubykube/peatio/blob/master/app/models/market.rb#L107

**Comment by esoftllp** [comment]
Version is updated.Please check model is correct.

![capture](https://user-images.githubusercontent.com/32095632/39290915-d3691144-494e-11e8-9b99-04cc239893dc.PNG)

**Comment by esoftllp** [comment]
Or let me know if i can use master branch for both Admin and Trading UI

**Comment by esoftllp** [comment]
I have used master branch for both but still same issue

**Comment by esoftllp** [comment]
@yivo Can you please help me

**Comment by yivo** [comment]
@esoftllp Please ask someone in Telegram chat. https://t.me/peatio

We are running lot of peatio 1.7 and everything works fine.
