### ISSUE TITLE
Error {"error":{"code":1001,"message":"market does not have a valid value"}}

### ISSUE THREAD

**Issue by archana209** [rubykube/peatio-trading-ui#29]
I cant load the market data (it keeps saying loading....)
Errors I could see are below

![image](https://user-images.githubusercontent.com/36262402/39309551-2fbfa32a-4960-11e8-8f84-d13d0a5413ae.png)

Any ideas

Thanks

**Comment by yivo** [comment]
Hi @archana209 

You should use the same versions for both peatio & trading UI. For example, Peatio 1.7 and trading UI 1.7.

**Comment by archana209** [comment]
Hello @yivo , my versions are in sync both trading-ui and peatio are on 1-7-stable.

**Comment by jdowning100** [comment]
I have the same issue. I am running workbench with peatio 1.8 and trading ui 1.8. Please do not close issues that have not been solved.

**Comment by yivo** [comment]
@jdowning100 Avoid running `db:schema:load` or `db:setup`. Try `db:drop db:create db:migrate db:seed`.
