### ISSUE TITLE
Dropdown Fund in trading UI show all

### ISSUE THREAD

**Issue by myujang** [rubykube/peatio-trading-ui#36]
i am using 1-8-stable. Certain coin, like XRP is not visible in currencies. which meant it not setup. In fund page profile also doesnt show XRP.
But when in trading ui, it show all including the coins that have status invisible.

<img width="331" alt="screen shot 2018-05-22 at 2 20 42 am" src="https://user-images.githubusercontent.com/132091/40323161-27455e2c-5d67-11e8-99fe-0aa24356fc5e.png">

Is this normal behaviour default in trading-ui?

**Comment by yivo** [comment]
Market#visible is not supported right now.

**Comment by yivo** [comment]
https://github.com/rubykube/peatio/issues/817
