### ISSUE TITLE
TypeError in Markets#show

### ISSUE THREAD

**Issue by ArifulIslamSonnet** [rubykube/peatio-trading-ui#37]
Just tried to install the latest peatio from this repository. Every time, I am getting same error. tried a lot to fix but so solution. anyone there to tell about this issue? 

<img src="https://s5.postimg.cc/jao2vh5zr/screenshot_2018_05_22.png"/>

Thanks in advance.

**Comment by yivo** [comment]
See this issue please: https://github.com/rubykube/peatio/issues/1104
