### ISSUE TITLE
Trade page is broken under high load

### ISSUE THREAD

**Issue by shal** [rubykube/peatio-trading-ui#38]
![img-1527003012](https://user-images.githubusercontent.com/15674738/40374777-6ff55344-5df2-11e8-8ba4-b5c83af8c069.png)

**Comment by ritesh-skyach** [comment]
@yivo I have checked this issue and this is working fine.

**Comment by ashanaakh** [comment]
@ritesh-skyach I need to check it under high load.

**Comment by ritesh-skyach** [comment]
@ashanaakh Sure, Let me know if there is an issue.

**Comment by ritesh-skyach** [comment]
@yivo @ashanaakh I have tested this using https://github.com/rubykube/toolbox and seems to be working fine

**Comment by yivo** [comment]
See https://youtu.be/_43nzxwe_tc
