### ISSUE TITLE
Candlestick bar is visible in line view

### ISSUE THREAD

**Issue by pkucherenk0** [rubykube/peatio-trading-ui#45]
Open some market with a Candlestick graphics (http://peatio.trade/trading/uahusd with timeline 1w).
![selection_261](https://user-images.githubusercontent.com/38254545/40418737-d85303ac-5e8b-11e8-917d-59d05b4c8c32.png)
Change to the Line graphics and take a look at the place where the Candlestick was.
![selection_260](https://user-images.githubusercontent.com/38254545/40418764-e512abba-5e8b-11e8-88e8-387a88eea7b5.png)

**Comment by yivo** [comment]
Closed by #49.
