### ISSUE TITLE
Ask/Bid with high precision ist fitting the page and get on top of each other. 

### ISSUE THREAD

**Issue by pkucherenk0** [rubykube/peatio-trading-ui#47]
![selection_264](https://user-images.githubusercontent.com/38254545/40423273-b9c88290-5e9a-11e8-8af9-3a0827773797.png)

**Comment by yivo** [comment]
Can we increase widths where needed?

**Comment by dinesh-skyach** [comment]
@yivo we can increase width but this will break if we increase more precision for market trading. 

In Addition I have set the width according to 8 precision.

**Comment by yivo** [comment]
Closed by #63.
