### ISSUE TITLE
URLs that need to reference PLATFORM_ROOT_URL

### ISSUE THREAD

**Issue by sramsden** [rubykube/peatio-trading-ui#5]
I found that when I ran peatio-trading-ui locally (on port 3001) that I had to make changes to ensure that all resources (from peatio) were available.
The following is the list of things I needed to prepend the PLATFORM_ROOT_URL to..

/markets/
/languages/
/pusher/auth
/api/v2/k_with_pending_trades.json

I'm not 100% sure if they should all be changed, so please investigate and change those that should be.

**Comment by yivo** [comment]
Hi @sramsden 

You are doing it totally wrong. Please, go to https://github.com/rubykube/peatio/blob/master/docs/releases/1.5.0.md and read with attention. Also please check similar issue on Peatio: https://github.com/rubykube/peatio/issues/713

If your question is resolved please close the ticker. Thanks.

**Comment by sramsden** [comment]
> The trick is that both Peatio and Trading UI are deployed on the same domain but are served conditionally by NGINX reverse proxy depending on the request path.

Bingo!  You may like to add the URL to the peatio release notes to the peatio-trading-ui readme.. haha.
