### ISSUE TITLE
Fix colors of currencies.

### ISSUE THREAD

**Issue by pkucherenk0** [rubykube/peatio-trading-ui#53]
Make them same color with price, amount and total.
![selection_274](https://user-images.githubusercontent.com/38254545/40492139-81a0e536-5f78-11e8-8e1c-bc863600de1c.png)

**Comment by ZohairZaman** [comment]
@pkucherenk0 could you guide me on how to link this with peatio if i deployed via a container. The trade screen does not open for me when I click on the trade section

**Comment by yivo** [comment]
Fixed in #56.
