### ISSUE TITLE
The price hint should be red.

### ISSUE THREAD

**Issue by pkucherenk0** [rubykube/peatio-trading-ui#55]
Please, make color for "Low" and "High" price hint red.
![selection_290](https://user-images.githubusercontent.com/38254545/40651738-1ef97f72-633f-11e8-879a-04acbd6d486e.png)
![selection_289](https://user-images.githubusercontent.com/38254545/40651755-2827f74a-633f-11e8-875f-2955bdb0798d.png)

**Comment by yivo** [comment]
Closed by #57.
