### ISSUE TITLE
Highcharts-series is missing.

### ISSUE THREAD

**Issue by pkucherenk0** [rubykube/peatio-trading-ui#64]
At the moment highcharts-series is missing:
![selection_322](https://user-images.githubusercontent.com/38254545/40980228-963fbcb2-68e0-11e8-92e1-70303a494a56.png)
Should be like on the next screenshot (blue line):
![selection_323](https://user-images.githubusercontent.com/38254545/40980288-aabd0cc6-68e0-11e8-962a-c6bbda2b7cd7.png)

**Comment by yivo** [comment]
Fixed in #66.
