### ISSUE TITLE
The color changing bid/ask upon crating new orders or trades

### ISSUE THREAD

**Issue by pkucherenk0** [rubykube/peatio-trading-ui#69]
The color of bid/ask order should change om a brief period of time.
Creating new order on the same side with the same price will stack in one line, upon that action the order should change color to the green fro a brief second. Same with the opposite sides when bid/ask orders are met, with the red color.

The example can be found here:
https://streamable.com/q430n

**Comment by yivo** [comment]
Closed by #71.
