### ISSUE TITLE
Little Help

### ISSUE THREAD

**Issue by ghost** [rubykube/peatio-trading-ui#96]
when running the peatio-trading ui, i got this page as if the styles were missing, that is the css. was it my nginx because i had difficult time configuring ssl for nginx. please help
![azaz](https://user-images.githubusercontent.com/15851793/44762591-1e9da900-ab37-11e8-9727-fbf80d6aa203.png)

**Comment by ghost** [comment]
what am i missing? think think

**Comment by ghost** [comment]
solved

**Comment by cryptobot123** [comment]
how you solved?  i have the same problem
